### ISSUE TITLE
Panic button make crash discord

### ISSUE THREAD

**Issue by Bricklou** [LandenStephenss/Panikk#13]
Discord crash and throw me the error below when I press the panic shortcut. I have to refresh the client to make it work again.

![image](https://user-images.githubusercontent.com/15181236/155811447-a0fce16b-1496-4e42-b771-995a2c763b62.png)

**Comment by LandenStephenss** [comment]
This doesn't seem to be panikk related. Since panikk never tries to destructure an app property
