### ISSUE TITLE
Timestamps from other peoples' messages shift to new line when toggling on

### ISSUE THREAD

**Issue by m-sterling** [LandenStephenss/Panikk#6]
When I activate Panikk, it shifts the timestamps on some messages down to the next line.

Before activating: https://msterling.dev/i/place-shadow-oe-timothy-hypothetical-8279.png
After activating: https://msterling.dev/i/must-ms-fly-converter-jade-2393.png

Any idea what this could be?

**Comment by LandenStephenss** [comment]
That's because you have a plugin that add's something next to timestamps. Switching channels after using Panikk should fix this.
